packages:
  - 'packages/*'
  - 'packages-private/*'
  - 'packages-jsx/*'

catalog:
  '@babel/code-frame': ^8.0.0
  '@babel/core': ^8.0.1
  '@babel/helper-module-imports': ^8.0.0
  '@babel/helper-plugin-utils': ^8.0.1
  '@babel/parser': ^7.29.7
  '@babel/plugin-syntax-jsx': ^8.0.1
  '@babel/plugin-syntax-typescript': ^8.0.3
  '@babel/preset-env': ^8.0.2
  '@babel/standalone': ^8.0.4
  '@babel/template': ^8.0.0
  '@babel/types': ^7.29.7
  'vite': ^8.1.0
  '@vitejs/plugin-vue': ^6.0.7
  '@vitejs/plugin-vue-jsx': ^5.1.6
  '@rolldown/plugin-babel': ^0.2.3
  '@types/babel__standalone': ^7.1.9
  '@vue/shared': ^3.5.40
  'assert': ^2.1.0
  'monaco-editor': ^0.56.0
  'tsdown': ^0.22.14
  'vue': ^3.5.40

allowBuilds:
  '@swc/core': true
  'esbuild': true
  'puppeteer': true
  'simple-git-hooks': true
  'unrs-resolver': true

dedupePeers: true

peerDependencyRules:
  allowedVersions:
    'typescript-eslint>eslint': '^9.0.0'
    '@typescript-eslint/eslint-plugin>eslint': '^9.0.0'
    '@typescript-eslint/parser>eslint': '^9.0.0'
    '@typescript-eslint/type-utils>eslint': '^9.0.0'
    '@typescript-eslint/utils>eslint': '^9.0.0'

minimumReleaseAge: 1440
